media: src/media
content:
  - name: questions
    label: Questions
    path: src/content/questions
    type: collection
    view:
      fields: [question, answer]
    fields:
      - name: image
        label: Image
        type: image
        required: true
