media: src/media
content:
  - name: questions
    label: Questions
    path: src/content/questions
    type: collection
    view:
      fields: [question, answer]
    fields:
      - name: question
        label: Question
        type: text
        required: true
      - name: answer
        label: Answer
        type: text
        required: true
      - name: to
        label: Directed To
        type: text
      - name: date
        label: Date
        type: date
      - name: image
        label: Image
        type: image
        required: true
      - name: notes
        label: Notes
        type: rich-text
